# see https://github.com/broadway/broadway-bundle

broadway:
    # service definition ids implementing Broadway\Serializer\Serializer
    serializer:
        payload:   broadway.simple_interface_serializer
        readmodel: broadway.simple_interface_serializer
        metadata:  broadway.simple_interface_serializer

    command_handling:
        dispatch_events: true

        # a service definition id implementing Psr\Log\LoggerInterface
        logger: ~

    saga:
        enabled: false

        # a service definition id implementing Broadway\Saga\State\RepositoryInterface
        state_repository: broadway.saga.state.in_memory_repository
