version: "3"
services:
  app:
    build: ./docker/app
    volumes:
      - .:/app
    ports:
      - 8100:8100

  elasticsearch:
      build: ./docker/elasticsearch
      environment:
        - http.host=0.0.0.0
        - transport.host=127.0.0.1
      ports:
        - 9200:9200
